import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/component/Header";
import SubHeader from "@/component/SubHeader";
import SecondaryNav from "@/component/SecondaryNav";
import Footer from "@/component/Footer";
import { Providers } from "./providers";

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} h-full antialiased`}
      >
      <body className={`min-h-full flex flex-col pt-40 md:pt-40`}>
        <Providers>
          <Header />
          <SubHeader />
          <SecondaryNav />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
